
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/Component/Header/Header";
import Footer from "@/Component/Footer/Footer";
import LoadingPlane from "@/Component/Loading/LoadingPlane";
import ReduxProvider from "@/redux/_provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Travel Agency",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  return (
    // <ReduxProvider>
    <html lang="en">
      <body
        className={`flex flex-col justify-between h-[100vh] ${geistSans.variable} ${geistMono.variable} antialiased`}
        cz-shortcut-listen="true"
      >
        <Header />
        {/* <LoadingPlane> */}
          {children}
          {/* </LoadingPlane> */}
        <Footer />
      </body>
    </html>
    // </ReduxProvider>
  );
};